//! Programmatic generation of commented default configs.
//!
//! Single source of truth: Rust doc comments (lifted into JSON Schema
//! descriptions by schemars) + a `Default` impl. The emitter walks the
//! serialized default value for structure/order and consults the schema
//! alongside for descriptions, so generated configs can never drift from
//! the types they represent.
//!
//! Invariant: `parse_str(&generate_default::<T>(..)) == T::default()`
//! whenever RON round-trips T faithfully.

use schemars::JsonSchema;
use serde::Serialize;
use serde::de::DeserializeOwned;

const INDENT: &str = "    ";
/// Wrap comment lines at roughly this width.
const COMMENT_WIDTH: usize = 72;

#[derive(Debug, thiserror::Error)]
pub enum GenerateError {
    #[error("value/schema mismatch at {path}: {message}")]
    Mismatch { path: String, message: String },
}

fn mismatch(path: &str, message: impl Into<String>) -> GenerateError {
    GenerateError::Mismatch {
        path: path.to_string(),
        message: message.into(),
    }
}

/// Generate a full commented RON config file for `T` from its `Default`
/// implementation and doc comments.
///
/// `tool_hint` appears in the header, e.g. `"quiver-chat --sample-config"`.
pub fn generate_default<T>(tool_hint: &str) -> Result<String, GenerateError>
where
    T: Default + Serialize + DeserializeOwned + JsonSchema + PartialEq,
{
    let value = serde_json::to_value(T::default()).map_err(|e| GenerateError::Mismatch {
        path: String::new(),
        message: format!("serializing default failed: {e}"),
    })?;
    let schema =
        serde_json::to_value(schemars::schema_for!(T)).map_err(|e| GenerateError::Mismatch {
            path: String::new(),
            message: format!("schema serialization failed: {e}"),
        })?;

    // Round-trip check: the emitted text must parse back to the same default.
    let body = emit_root(&value, &schema)?;
    let text = format!("{}{}", root_header(&schema, tool_hint), body);
    let parsed: T = crate::parse_str(&text).map_err(|e| GenerateError::Mismatch {
        path: String::new(),
        message: format!("generated output failed to parse (bug): {e}"),
    })?;
    if parsed != T::default() {
        return Err(mismatch(
            "",
            "generated output does not round-trip to Default",
        ));
    }
    Ok(text)
}

fn root_header(schema: &serde_json::Value, tool_hint: &str) -> String {
    let mut out = String::from("// ");
    out.push_str(
        &wrap_comment(
            schema
                .get("title")
                .and_then(|v| v.as_str())
                .unwrap_or("Configuration"),
        )
        .join("\n// "),
    );
    out.push('\n');
    if let Some(desc) = description(schema) {
        for line in wrap_comment(&desc) {
            out.push_str("// ");
            out.push_str(&line);
            out.push('\n');
        }
    }
    out.push_str(&format!(
        "// Generated by `{tool_hint}` — edit freely; validate with the same tool.\n"
    ));
    out
}

/// Emit the top-level value as a full RON document body.
fn emit_root(
    value: &serde_json::Value,
    schema: &serde_json::Value,
) -> Result<String, GenerateError> {
    let defs = schema.get("$defs");
    let resolved = resolve_ref(schema, defs);
    let mut out = String::new();
    emit_value(&mut out, value, resolved, defs, 0, "")?;
    out.push('\n');
    Ok(out)
}

/// Follow `$ref` pointers into $defs (single-hop, name-based).
fn resolve_ref<'a>(
    node: &'a serde_json::Value,
    defs: Option<&'a serde_json::Value>,
) -> &'a serde_json::Value {
    if let Some(reference) = node.get("$ref").and_then(|v| v.as_str()) {
        let name = reference.rsplit('/').next().unwrap_or(reference);
        if let Some(defs) = defs.and_then(|d| d.get(name)) {
            return defs;
        }
    }
    node
}

fn description(schema_node: &serde_json::Value) -> Option<String> {
    schema_node
        .get("description")
        .and_then(|v| v.as_str())
        .map(str::to_string)
}

/// Wrap a doc-comment string into comment-ready lines (~COMMENT_WIDTH),
/// preserving author line breaks and collapsing single newlines into
/// spaces like rustdoc does.
fn wrap_comment(text: &str) -> Vec<String> {
    let mut lines = Vec::new();
    for paragraph in text.split('\n') {
        let mut current = String::new();
        for word in paragraph.split_whitespace() {
            if !current.is_empty() && current.chars().count() + word.len() + 1 > COMMENT_WIDTH {
                lines.push(std::mem::take(&mut current));
            }
            if !current.is_empty() {
                current.push(' ');
            }
            current.push_str(word);
        }
        lines.push(current);
    }
    lines
}

fn push_comment(out: &mut String, indent: usize, desc: &str) {
    for line in wrap_comment(desc) {
        for _ in 0..indent {
            out.push_str(INDENT);
        }
        out.push_str("// ");
        out.push_str(&line);
        out.push('\n');
    }
}

fn push_indent(out: &mut String, indent: usize) {
    for _ in 0..indent {
        out.push_str(INDENT);
    }
}

/// Emit one field of an object: comments + `name: <value>,`
fn emit_field(
    out: &mut String,
    key: &str,
    value: &serde_json::Value,
    field_schema: &serde_json::Value,
    defs: Option<&serde_json::Value>,
    indent: usize,
    path: &str,
) -> Result<(), GenerateError> {
    // NOTE: schemars 1.x places FIELD doc comments on the property node
    // itself, next to any $ref (not on the $defs entry) — read the
    // description BEFORE resolving.
    if let Some(desc) = description(field_schema) {
        push_comment(out, indent, &desc);
    }
    let resolved = resolve_ref(field_schema, defs);
    push_indent(out, indent);
    out.push_str(key);
    out.push_str(": ");
    emit_value(out, value, resolved, defs, indent, path)?;
    out.push_str(",\n");
    Ok(())
}

/// Nullability detection: schemars renders Option<T> fields as either
/// `"type": ["T","null"]` or anyOf [T, null] depending on version shape.
fn is_nullable(schema_node: &serde_json::Value) -> bool {
    if let Some(types) = schema_node.get("type").and_then(|v| v.as_array())
        && types.iter().any(|t| t.as_str() == Some("null"))
    {
        return true;
    }
    if let Some(any_of) = schema_node.get("anyOf").and_then(|v| v.as_array())
        && any_of
            .iter()
            .any(|s| s.get("type").and_then(|t| t.as_str()) == Some("null"))
    {
        return true;
    }
    false
}

/// The non-null variant of a nullable schema (for Some(..) wrapping).
/// Owned because the type-array form needs null stripped from a copy.
fn unwrap_nullable(schema_node: &serde_json::Value) -> serde_json::Value {
    if let Some(any_of) = schema_node.get("anyOf").and_then(|v| v.as_array()) {
        for variant in any_of {
            if variant.get("type").and_then(|t| t.as_str()) != Some("null") {
                return variant.clone();
            }
        }
    }
    if let Some(types) = schema_node.get("type").and_then(|v| v.as_array()) {
        let non_null: Vec<_> = types
            .iter()
            .filter(|t| t.as_str() != Some("null"))
            .cloned()
            .collect();
        if !non_null.is_empty() {
            let mut stripped = schema_node.clone();
            stripped["type"] = serde_json::Value::Array(non_null);
            return stripped;
        }
    }
    schema_node.clone()
}

fn emit_value(
    out: &mut String,
    value: &serde_json::Value,
    schema_node: &serde_json::Value,
    defs: Option<&serde_json::Value>,
    indent: usize,
    path: &str,
) -> Result<(), GenerateError> {
    // JSON has no Some() wrapper — reconstruct it for nullable fields so
    // RON parses (Option fields REQUIRE explicit Some(..)).
    if !value.is_null() && is_nullable(schema_node) {
        out.push_str("Some(");
        let inner = unwrap_nullable(schema_node);
        emit_value(out, value, &inner, defs, indent, path)?;
        out.push(')');
        return Ok(());
    }

    match value {
        serde_json::Value::Object(map) => {
            let props = schema_node.get("properties").and_then(|p| p.as_object());

            if let Some(props) = props {
                // Struct: parens + declaration-ordered fields. Fields that
                // serialization OMITTED (skip_serializing_if on Options)
                // are still emitted as `key: None` — generated configs must
                // expose the full interface for discoverability.
                out.push_str("(\n");
                for (key, field_schema) in props {
                    // Pass the UNRESOLVED property node: descriptions sit
                    // next to $ref on the property itself; emit_field
                    // resolves for the value emission.
                    let resolved_field = resolve_ref(field_schema, defs);
                    let val = match map.get(key) {
                        Some(v) => v,
                        None => {
                            if !is_nullable(resolved_field) {
                                return Err(mismatch(
                                    path,
                                    format!("field {key:?} omitted from defaults but not nullable"),
                                ));
                            }
                            &serde_json::Value::Null
                        }
                    };
                    emit_field(out, key, val, field_schema, defs, indent + 1, path)?;
                }
                push_indent(out, indent);
                out.push(')');
            } else {
                // Free-form map (HashMap etc.): RON braces + quoted keys.
                let value_schema = resolve_ref(
                    schema_node
                        .get("additionalProperties")
                        .unwrap_or(&serde_json::Value::Null),
                    defs,
                );
                if map.is_empty() {
                    out.push_str("{}");
                    return Ok(());
                }
                out.push_str("{\n");
                for (key, val) in map {
                    push_indent(out, indent + 1);
                    out.push_str(&escape_ron_string(key));
                    out.push_str(": ");
                    emit_value(
                        out,
                        val,
                        value_schema,
                        defs,
                        indent + 1,
                        &format!("{path}.{key}"),
                    )?;
                    out.push_str(",\n");
                }
                push_indent(out, indent);
                out.push('}');
            }
        }
        serde_json::Value::Array(items) => {
            let item_schema = resolve_ref(
                schema_node.get("items").unwrap_or(&serde_json::Value::Null),
                defs,
            );
            if items.is_empty() {
                out.push_str("[]");
                return Ok(());
            }
            out.push_str("[\n");
            for item in items {
                push_indent(out, indent + 1);
                emit_value(out, item, item_schema, defs, indent + 1, path)?;
                out.push_str(",\n");
            }
            push_indent(out, indent);
            out.push(']');
        }
        serde_json::Value::String(s) => out.push_str(&escape_ron_string(s)),
        serde_json::Value::Number(n) => out.push_str(&n.to_string()),
        serde_json::Value::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
        serde_json::Value::Null => {
            if is_nullable(schema_node) {
                out.push_str("None");
            } else {
                return Err(mismatch(path, "null encountered on non-nullable field"));
            }
        }
    }
    Ok(())
}

/// Escape a Rust/RON string literal body (quote + backslash + controls).
pub(crate) fn escape_ron_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
