//! Integration tests for generate_default: hand-written golden output,
//! round-trip invariant, comment presence.

use quiver_config::{generate_default, parse_str};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

#[derive(Debug, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
/// Test config exercising every emitter branch.
struct Fixture {
    /// The host and port to bind.
    listen: String,
    /// How many retries before giving up.
    retries: u32,
    /// Whether the thing is on.
    enabled: bool,
    /// Optional path; None renders as `None`.
    data_dir: Option<String>,
    /// Skipped-when-none field; generator must still surface it.
    #[serde(skip_serializing_if = "Option::is_none")]
    hidden: Option<u32>,
    /// Unit enum: serializes as string, RON wants bare identifier.
    #[serde(default)]
    mode: Mode,
    /// Nested group with its own docs.
    inner: Inner,
    /// Free-form labels.
    labels: std::collections::HashMap<String, String>,
}

#[derive(Debug, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
enum Mode {
    #[default]
    Prune,
    Scroll,
}

#[derive(Debug, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
struct Inner {
    /// A name inside a nested struct.
    name: String,
    /// An optional nested value.
    maybe: Option<u64>,
}

/// GOLDEN TEST — expected text written BY HAND from ground truth:
/// declaration-ordered fields, doc comments as // blocks, None for
/// empty options, RON paren style, trailing commas.
#[test]
fn generated_output_matches_hand_written_golden() {
    let out = generate_default::<Fixture>("test-tool").expect("generation succeeds");

    let expected = "\
// Fixture
// Test config exercising every emitter branch.
// Generated by `test-tool` — edit freely; validate with the same tool.
(
    // The host and port to bind.
    listen: \"\",
    // How many retries before giving up.
    retries: 0,
    // Whether the thing is on.
    enabled: false,
    // Optional path; None renders as `None`.
    data_dir: None,
    // Skipped-when-none field; generator must still surface it.
    hidden: None,
    // Unit enum: serializes as string, RON wants bare identifier.
    mode: prune,
    // Nested group with its own docs.
    inner: (
        // A name inside a nested struct.
        name: \"\",
        // An optional nested value.
        maybe: None,
    ),
    // Free-form labels.
    labels: {},
)
";

    // On drift this prints raw left/right — readable enough for one line
    // of divergence; anything subtler gets diagnosed, not tooling-built.
    assert_eq!(out, expected);
}

/// THE invariant: generated text parses back to exactly T::default().
#[test]
fn generated_output_round_trips_to_default() {
    let out = generate_default::<Fixture>("test-tool").expect("generation succeeds");
    let parsed: Fixture = parse_str(&out).expect("generated must parse");
    assert_eq!(parsed, Fixture::default());
}
